### ISSUE TITLE
Is there a way to simulate failures?

### ISSUE THREAD

**Issue by mjmaix** [cartant/firebase-nightlight#16]
How should we simulate error for firebase database and authentication methods? I would like to know if anyone is doing something similar or workaround.

For example:

```
firebase.auth().signInWithEmailAndPassword(email, password)
    .catch(function(error) {
   //  I want to test this
});

adaNameRef.set({ first: 'Ada', last: 'Lovelace' })
  .then(function() {
    console.log('Synchronization succeeded');
  })
  .catch(function(error) {
   //  I want to test this
  });
```

**Comment by cartant** [comment]
Yes.

You can test `signInWithEmailAndPassword` failures by [specifying identities when configuring the mock](https://github.com/cartant/firebase-nightlight/blob/v3.0.0/source/mock-auth-spec.ts#L18-L28) and by [using invalid credentials](https://github.com/cartant/firebase-nightlight/blob/v3.0.0/source/mock-auth-spec.ts#L343-L355) when calling `signInWithEmailAndPassword`.

And you can force read and write failures by embedding errors - using the `".error"` key - in the mock's database. This is mentioned in the [README](https://github.com/cartant/firebase-nightlight#forcing-database-errors) and there are numerous examples in the tests. The `set` test is [here](https://github.com/cartant/firebase-nightlight/blob/v3.0.0/source/mock-ref-spec.ts#L1884-L1898).

**Comment by mjmaix** [comment]
Thank you @Nicholas
