### ISSUE TITLE
3.1.1 firebase-interface.ts not found after npm install

### ISSUE THREAD

**Issue by takutoarao** [cartant/firebase-nightlight#51]
I execute `npm install` , but firebase-interface.ts not found.

Did you forget to run `npm publish`?

**Comment by layoutzweb** [comment]
Same here, jest says `Cannot find module 'firebase' from 'mock.js'`.

**Comment by cartant** [comment]
This should be fixed in 3.1.2.

Sorry not to notice your opening of this issue, @takutoarao
